### ISSUE TITLE
rehamove.hpp

### ISSUE THREAD

**Issue by Oryes** [worldwidemv/SimulinkBlock_RehaMove3#1]
Hello,

thank you for your code. That's very helpful. During running the  code I got the error:cannot open source file "rehamove.hpp":
|  #include "rehamove.hpp".

I couldn't find the file. I would be glad if you could  help me.

**Comment by worldwidemv** [comment]
Hello,

please be more specific because there is a lot of code .....
https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

I assume you are trying to compile one of the examples?
If so, which one? 

Is your current commit id:
239162e11f9219d04afbc0172b3b7325f40e8f12
( -> git log)

**Comment by Oryes** [comment]
Hello,

I am trying to compile the code from here: [https://github.com/worldwidemv/SimulinkBlock_RehaMove3] 
the file test_RehaMove3_block__LowLevel1_simple.slx

**Comment by worldwidemv** [comment]
Hello,

there was still a reference to an old header file in the Simulink diagram configuration, under "Simulation Target".

Please see if the last commit: c4df3782006fcbf1e3317bdbc7fa2ba9e34cd52e fixes the issue.

**Comment by Oryes** [comment]
Hello,

Diagnostic in Simulink proposes: Fix the errors in your custom code or disable 'Import custom code' if your custom code has incompatibilities.
Would it be correct to disable?

**Comment by worldwidemv** [comment]
Which is exactly what the last commit did...
Did you test the last commit / the updated examples?

**Comment by Oryes** [comment]
Test your Installation

You can test if every works with one of the examples provided with the block. In Matlab, go to SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/ and open e.g. the file test_RehaMove3_block__LowLevel1_simple.slx

Build the diagram by clicking the "Build Model" button.

**Comment by Oryes** [comment]
then it gave this error

**Comment by worldwidemv** [comment]
I was asking if you updated to the newest version of these examples, aka commit: c4df378, and tested if the UPDATED examples work!
Please answere this question first....

Please also make sure Matlab/Simulink rebuilds everything, e.g. by deleting the old generated files. If you don't know what I am talking about, please first read the Simulink documentation about the Code Generation features and the "Build Model" Simulink feature.

**Comment by Oryes** [comment]
Sorry, I didn't see that you updated something 5 hours ago. I will do with newly generated files. Thank you for your prompt responses, and help.

**Comment by Oryes** [comment]
Hello,

Maybe I do something wrong. All steps  are as following:

1. git clone --recursive https://github.com/worldwidemv/SimulinkToolchain.git
2. Inside the main directory is the install script srt_InstallSRT.m
3. cd SimulinkToolchain/SimulinkLib_linux64/
git clone https://github.com/worldwidemv/SimulinkBlock_RehaMove3.git
4. In Matlab, go to SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/ and open e.g. the file test_RehaMove3_block__LowLevel1_simple.slx
5. Build the diagram by clicking the "Build Model" button.

**Comment by worldwidemv** [comment]
> Maybe I do something wrong.

Yes, you do not follow the installtion instructions for the RehaMove3 toolbox:
https://github.com/worldwidemv/SimulinkBlock_RehaMove3#get-the-library

Namely: 
* Get the library -> Updated Link from the Hasomed Website: https://www.rehamove.com/fileadmin/user_upload/RehaMove/ScienceMode/smpt_rm3_V3.2.4b.zip
* Run the Install Script, aka step 2 again


> All steps are as following:
> 
>     1. git clone --recursive https://github.com/worldwidemv/SimulinkToolchain.git
> 
>     2. Inside the main directory is the install script srt_InstallSRT.m
This, save the SimulinkToolchain directory in the Maltab path.
Did that work?


>     3. cd SimulinkToolchain/SimulinkLib_linux64/
>        git clone https://github.com/worldwidemv/SimulinkBlock_RehaMove3.git
Step 3b and 3c missing.

>     4. In Matlab, go to SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/ and open e.g. the file test_RehaMove3_block__LowLevel1_simple.slx
You probably don't even see the blocks like in the screenshot, right????


>     5. Build the diagram by clicking the "Build Model" button.

How am I supposed to help you with that information???
Do you think I have a cristal ball which tells me what the result of "Build Model" is?
Is it so hard to add the complete output of the build from the Diagnostic Viewer (Save Report)?
Did you even looked at the first link I send you about good Bugreports?



### I did it so on an new Ubuntu 18.04 installation:
```
>> ver
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.1.0.441655 (R2016b)
MATLAB License Number: 
Operating System: Linux 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.1         (R2016b)
Simulink                                              Version 8.8         (R2016b)
Control System Toolbox                                Version 10.1        (R2016b)
Embedded Coder                                        Version 6.11        (R2016b)
MATLAB Coder                                          Version 3.2         (R2016b)
Simulink Coder                                        Version 8.11        (R2016b)
Stateflow                                             Version 8.8         (R2016b)
System Identification Toolbox                         Version 9.5         (R2016b)
>> 
```

```
>> srt_InstallSRT

Installation of the Soft-Realtime Simulink Toolbox
===================================================

### Running ERT_Linux installation:
   -> ERT_LINUX Target Path Setup Complete.


### Running install script for "SimulinkBlock_RehaMove3": install_LIB_RehaMove3.m
SMPT library directory "incRehaMove_LibV3.2_lin_x86_64" added.
TODO: copy udev rules
   -> done.


====================================================================
Running the build scripts now. You can run the build script also with the "srt_CreateLib" command.

Building the "Soft-Realtime Simulink Toolbox" ....

   -> Closing the Simulink library (this can take a while) ...  done
   -> Running the individual build scripts ...

** LIB_RehaMove3 *******************************

### Start Compiling sfunc_RehaMove3_01
    mex('-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated', '-c', '-outdir', '/tmp/tp5312d6a7_aa6a_49ae_ac4f_f12b5f3aa4fc', '/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp')
Building with 'g++'.
/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp: In member function ‘void nsRehaMove3_SMPT_32X_01::RehaMove3::PutLLChannelResponse(uint8_t, Smpt_Result, Smpt_Channel)’:
/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: warning: ‘     -> UNDEFINED Error => P...’ directive output may be truncated writing 41 bytes into a region of size between 1 and 1000 [-Wformat-truncation=]
      snprintf(ErrorString, sizeof(ErrorString), "%s     -> UNDEFINED Error => Pulse Number: %d; Channel: %d (%s) Result: %d\n",
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: directive argument in the range [1, 256]
/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: directive argument in the range [-127, 128]
/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: using the range [-2147483648, 2147483647] for directive argument
In file included from /usr/include/stdio.h:867,
                 from /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.hpp:34,
                 from /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:23:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 69 or more bytes (assuming 1073) into a destination of size 1000
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

MEX completed successfully.
    mex('-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated', '-c', '-outdir', '/tmp/tp5312d6a7_aa6a_49ae_ac4f_f12b5f3aa4fc', '/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/block_RehaMove3_01.cpp')
Building with 'g++'.
MEX completed successfully.
    mex('sfunc_RehaMove3_01.cpp', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level', '-I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated', '/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/lib/libsmpt.a', '-cxx', '/tmp/tp5312d6a7_aa6a_49ae_ac4f_f12b5f3aa4fc/RehaMove3Interface_SMPT32X.o', '/tmp/tp5312d6a7_aa6a_49ae_ac4f_f12b5f3aa4fc/block_RehaMove3_01.o')
Building with 'g++'.
MEX completed successfully.
### Finish Compiling sfunc_RehaMove3_01
### Exit

************************************************


Building the "Soft-Realtime Simulink Toolbox" is done!


====================================================================
The installation of the "Soft-Realtime Simulink Toolbox" is done.

You can run the build script again with the "srt_CreateLib" command (necessary after upgrades)!

>>
```


```
=== Build (Elapsed: 14 sec) ===
    ### Starting build procedure for model: test_RehaMove3_block__LowLevel1_simple
    ### Generating code into build folder: /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux
    Warning:In release, R2015b, the "Generate preprocessor conditionals" global setting was removed from the Model Configuration Parameters > Code Generation (ert) > Interface pane. Generation of preprocessor conditionals is now a strict property of the individual variant blocks. You can run slConfigureVariantGPC('test_RehaMove3_block__LowLevel1_simple','Disable all') to transfer the prior release global setting to the individual variant blocks. This will make your model behave the same way it did in the prior version of Simulink. Alternatively, you can run set_param('test_RehaMove3_block__LowLevel1_simple','GeneratePreprocessorConditionals','Use local settings') to eliminate this warning and then manually configure the individual variant blocks' "Generate preprocessor conditionals" setting.
    ### Invoking Target Language Compiler on test_RehaMove3_block__LowLevel1_simple.rtw
    ### Using System Target File: /home/control2/RehaMove3_Test/SimulinkToolchain/ert_linux/ert_linux/ert_linux.tlc
    ### Loading TLC function libraries
    ### Initial pass through model to cache user defined code
    .
    ### Caching model source code
    ### Writing header file test_RehaMove3_block__LowLevel1_simple.h
    ### Writing header file test_RehaMove3_block__LowLevel1_simple_types.h
    .
    ### Writing header file rtwtypes.h
    ### Writing header file multiword_types.h
    ### Writing source file test_RehaMove3_block__LowLevel1_simple.cpp
    ### Writing header file test_RehaMove3_block__LowLevel1_simple_private.h
    ### Writing source file test_RehaMove3_block__LowLevel1_simple_data.cpp
    .
    ### Writing header file rtmodel.h
    ### Writing source file ert_main.cpp
    ### TLC code generation complete.
    ### Generating TLC interface API.
    ### Creating data type transition file test_RehaMove3_block__LowLevel1_simple_dt.h
    ### Creating project marker file: rtw_proj.tmw
    .
    ### Processing Template Makefile: /home/control2/RehaMove3_Test/SimulinkToolchain/ert_linux/ert_linux/ert_linux.tmf
    ### Creating test_RehaMove3_block__LowLevel1_simple.mk from /home/control2/RehaMove3_Test/SimulinkToolchain/ert_linux/ert_linux/ert_linux.tmf
    ### Building test_RehaMove3_block__LowLevel1_simple: /home/bin/MATLAB/_R2016b/bin/glnxa64/gmake -f test_RehaMove3_block__LowLevel1_simple.mk OPTS="-DON_TARGET_WAIT_FOR_START=0 -DWITH_HW"  OPTIMIZATION_FLAGS=-O3 GENERATE_ASAP2=0 ISPROTECTINGMODEL=NOTPROTECTING SINGLE_LINE_COMMENTS=1
    gcc -c -fwrapv -fPIC  -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils/rtiostream_utils.c"
    g++ -c -std=c++98 -pedantic -Wno-long-long -fwrapv -fPIC   -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp"
    /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp: In member function ‘void nsRehaMove3_SMPT_32X_01::RehaMove3::PutLLChannelResponse(uint8_t, Smpt_Result, Smpt_Channel)’:
    /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: warning: ‘     -> UNDEFINED Error => P...’ directive output may be truncated writing 41 bytes into a region of size between 1 and 1000 [-Wformat-truncation=]
          snprintf(ErrorString, sizeof(ErrorString), "%s     -> UNDEFINED Error => Pulse Number: %d; Channel: %d (%s) Result: %d\n",
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: directive argument in the range [1, 12]
    /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: directive argument in the range [-127, 128]
    /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: using the range [-2147483648, 2147483647] for directive argument
    In file included from /usr/include/stdio.h:867,
                     from /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.hpp:34,
                     from /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:23:
    /usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 69 or more bytes (assuming 1072) into a destination of size 1000
       return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            __bos (__s), __fmt, __va_arg_pack ());
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    g++ -c -std=c++98 -pedantic -Wno-long-long -fwrapv -fPIC   -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/block_RehaMove3_01.cpp"
    g++ -c -std=c++98 -pedantic -Wno-long-long -fwrapv -fPIC   -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "ert_main.cpp"
    In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                     from /usr/include/stdio.h:27,
                     from ert_main.cpp:19:
    Warning:/usr/include/features.h:185:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
     # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
       ^~~~~~~
    g++ -c -std=c++98 -pedantic -Wno-long-long -fwrapv -fPIC   -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "test_RehaMove3_block__LowLevel1_simple_data.cpp"
    g++ -c -std=c++98 -pedantic -Wno-long-long -fwrapv -fPIC   -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "test_RehaMove3_block__LowLevel1_simple.cpp"
    gcc -c -fwrapv -fPIC  -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common/ext_svr.c"
    gcc -c -fwrapv -fPIC  -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common/updown.c"
    gcc -c -fwrapv -fPIC  -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common/ext_work.c"
    gcc -c -fwrapv -fPIC  -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common/rtiostream_interface.c"
    gcc -c -fwrapv -fPIC  -DON_TARGET_WAIT_FOR_START=0 -DWITH_HW -DEXT_MODE -DGLNXA64  -O3 -DMODEL=test_RehaMove3_block__LowLevel1_simple -DNUMST=1 -DNCSTATES=0 -DUNIX -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=1 -DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DCLASSIC_INTERFACE=0 -DMT=0 -I. -I.. -I/home/bin/MATLAB/_R2016b/extern/include -I/home/bin/MATLAB/_R2016b/simulink/include -I/home/bin/MATLAB/_R2016b/rtw/c/src -I/home/bin/MATLAB/_R2016b/rtw/c/src/ext_mode/common -I/home/bin/MATLAB/_R2016b/simulink/include/sf_runtime -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3/test_RehaMove3_block__LowLevel1_simple_ert_linux -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/examples/block_RehaMove3 -I/home/bin/MATLAB/_R2016b/toolbox/coder/rtiostream/src/utils -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level -I/home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated       "/home/bin/MATLAB/_R2016b/rtw/c/src/rtiostream/rtiostreamtcpip/rtiostream_tcpip.c"
    In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                     from /usr/include/stdio.h:27,
                     from /home/bin/MATLAB/_R2016b/rtw/c/src/rtiostream/rtiostreamtcpip/rtiostream_tcpip.c:24:
    Warning:/usr/include/features.h:185:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
     # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
       ^~~~~~~
    g++   -o ../test_RehaMove3_block__LowLevel1_simple RehaMove3Interface_SMPT32X.o block_RehaMove3_01.o ert_main.o ext_svr.o ext_work.o rtiostream_interface.o rtiostream_tcpip.o rtiostream_utils.o test_RehaMove3_block__LowLevel1_simple.o test_RehaMove3_block__LowLevel1_simple_data.o updown.o     /home/control2/RehaMove3_Test/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/lib/libsmpt.a    -lrt -lpthread -lm
    ### Created executable: ../test_RehaMove3_block__LowLevel1_simple
    ### Successful completion of build procedure for model: test_RehaMove3_block__LowLevel1_simple
    Build process completed successfully
```

Yes, Github Issues suck for this, but it is better than noting.... 
Use the markdown syntax for code:
https://guides.github.com/features/mastering-markdown/#examples -> Code
to make these outputs readable....

By the way, I spend now 30 minutes on fixing the bug and about 120 minutes on communicating with you ... ;-/

**Comment by Oryes** [comment]
> Get the library -> Updated Link from the Hasomed Website: 

I have the library in another folder that's why skipped this step.

**Comment by Oryes** [comment]
> You probably don't even see the blocks like in the screenshot, right????

I do see.

**Comment by Oryes** [comment]
> Step 3b and 3c missing.

3b: Next, you have to download the ScienceMode library from Hasomed.  ?
3c: Download and unzip the library in any folder ?

**Comment by Oryes** [comment]
> This, save the SimulinkToolchain directory in the Matlab path.

the SimulinkToolchain directory is not in the Matlab path. It is in the root.

**Comment by Oryes** [comment]
> This, save the SimulinkToolchain directory in the Maltab path

that's could be the  problem

**Comment by Oryes** [comment]
> This, save the SimulinkToolchain directory in the Maltab path.

Thank you  very much for your time, and effort. I hopeafter debuging the  code. it  could be useful for other reseracher too. I would be glad if we could complete that. Sorry for taking  your time.

**Comment by worldwidemv** [comment]
> > This, save the SimulinkToolchain directory in the Maltab path
> 
> that's could be the problem

What is in your opinition the "Matlab path" ?

**Comment by Oryes** [comment]
I assume between Change folder and Add to Path I  need to choose to Add to Path. If I choose to Add to Path then it gives the error. 

Reference to non-existent field 'runBuildScript'.

Error in srt_CreateLib (line 79)
        if (temp{iDir}.runBuildScript)_

**Comment by worldwidemv** [comment]
> What is in your opinition the "Matlab path" ?

It is amasing how you manage to never answer any of my questions!

Matlab Path = Where Matlab searches for functions and so one.
-> https://de.mathworks.com/help/matlab/ref/path.html
This is kind of very basic stuff, so you migth want to read a little bit more about Matlab and how to get started....


> I assume between Change folder and Add to Path I need to choose to Add to Path. If I choose to > Add to Path then it gives the error.
>
> Reference to non-existent field 'runBuildScript'.
> 
> Error in srt_CreateLib (line 79)
> if (temp{iDir}.runBuildScript)_

I have no idea what you last post means, but that is also not important, because the install script does all the work for you.

>> This, save the SimulinkToolchain directory in the Maltab path.
>> Did that work?

I wanted to know if you Matlab is set up correctly, so that the install script can run the 'savepath' command without any errors or warnings.
Otherwise, if you open Matlab again tomorrow, it will not work because Matlab can't find the toolbox scripts ...


Anyway, this is NOT your problem!, because after you have run the install script, the Matlab session is setup corretly to compile the examples!

Unfortunatly, I can NOT tell you what the problem is because YOU WON'T provide the output of the  Diagnostic Viewer after you press "Buiild Model".
Therefor, I will not respond anymore, until you provied this information.

Best Regards Markus

**Comment by Oryes** [comment]
> It is amasing how you manage to never answer any of my questions!

Dear Markus,

I don't ignore your question, at least consciously. I am trying to run the scripts last 3 months, there is one error is coming after another one. I am just quiet down, and  tried so many thing before contacting you.

**Comment by worldwidemv** [comment]
> I don't ignore your question, at least consciously.

:-) You might want to read our conversation again....

Anyway, Skype?

**Comment by Oryes** [comment]
```
srt_InstallSRT

Installation of the Soft-Realtime Simulink Toolbox
===================================================

### Running ERT_Linux installation:
   -> Warning: Unable to save path to file '/usr/local/MATLAB/R2016b/toolbox/local/pathdef.m'. You can save your
path to a different location by calling SAVEPATH with an input argument that specifies the full path. For
MATLAB to use that path in future sessions, save the path to 'pathdef.m' in your MATLAB startup folder. 
> In savepath (line 169)
  In ert_linux_setup (line 5)
  In srt_InstallSRT (line 19) 
ERT_LINUX Target Path Setup Complete.


### Running install script for "SimulinkBlock_RehaMove3": install_LIB_RehaMove3.m
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For
more information, click here. 
SMPT library directory "incRehaMove_LibV3.2_lin_x86_64" added.
TODO: copy udev rules
   -> done.

====================================================================
Running the build scripts now. You can run the build script also with the "srt_CreateLib" command.

Building the "Soft-Realtime Simulink Toolbox" ....

   -> Closing the Simulink library (this can take a while) ...  done
   -> Running the individual build scripts ...

** LIB_RehaMove3 *******************************

### Start Compiling sfunc_RehaMove3_01
    mex('-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated', '-c', '-outdir', '/tmp/tp0df69f9b_d036_4b35_bc70_66a07c74f2e7', '/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp')
Building with 'g++'.
/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp: In member function ‘void nsRehaMove3_SMPT_32X_01::RehaMove3::PutLLChannelResponse(uint8_t, Smpt_Result, Smpt_Channel)’:
/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: warning: ‘     -> UNDEFINED Error => P...’ directive output may be truncated writing 41 bytes into a region of size between 1 and 1000 [-Wformat-truncation=]
      snprintf(ErrorString, sizeof(ErrorString), "%s     -> UNDEFINED Error => Pulse Number: %d; Channel: %d (%s) Result: %d\n",
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: directive argument in the range [1, 256]
/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: directive argument in the range [-127, 128]
/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:2642:49: note: using the range [-2147483648, 2147483647] for directive argument
In file included from /usr/include/stdio.h:873,
                 from /home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.hpp:34,
                 from /home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/RehaMove3Interface_SMPT32X.cpp:23:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 69 or more bytes (assuming 1073) into a destination of size 1000
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

MEX completed successfully.
    mex('-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated', '-c', '-outdir', '/tmp/tp0df69f9b_d036_4b35_bc70_66a07c74f2e7', '/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src/block_RehaMove3_01.cpp')
Building with 'g++'.
MEX completed successfully.
    mex('sfunc_RehaMove3_01.cpp', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/srcRehaMove_LibV3.2/src', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/general', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/low-level', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/include/mid-level', '-I/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/auto_generated', '/home/ilida/SimulinkToolchain/SimulinkLib_linux64/SimulinkBlock_RehaMove3/incRehaMove_LibV3.2_lin_x86_64/lib/libsmpt.a', '-cxx', '/tmp/tp0df69f9b_d036_4b35_bc70_66a07c74f2e7/RehaMove3Interface_SMPT32X.o', '/tmp/tp0df69f9b_d036_4b35_bc70_66a07c74f2e7/block_RehaMove3_01.o')
Building with 'g++'.
MEX completed successfully.
### Finish Compiling sfunc_RehaMove3_01
### Exit

************************************************

Warning: Unable to save path to file '/usr/local/MATLAB/R2016b/toolbox/local/pathdef.m'. You can save your
path to a different location by calling SAVEPATH with an input argument that specifies the full path. For
MATLAB to use that path in future sessions, save the path to 'pathdef.m' in your MATLAB startup folder. 
> In savepath (line 169)
  In srt_CreateLib (line 186)
  In srt_InstallSRT (line 99) 

Building the "Soft-Realtime Simulink Toolbox" is done!


====================================================================
The installation of the "Soft-Realtime Simulink Toolbox" is done.

You can run the build script again with the "srt_CreateLib" command (necessary after upgrades)!`
```

**Comment by Oryes** [comment]
> Anyway, Skype?

That would be amazing! I can even share a TeamViewer account to connect. Can delete all data, and start from scratch. There were some issues cos of Matlab configurations. There are solved. I have both  Matlab2016b, and 2019a.

When would be convenient for you? My skype is Oryess.

Ilida.

**Comment by zahrabassiri** [comment]
hello, 
May I ask please to update the link for the library for Science Mode 3 (smpt_rm3_V3.2.4a)? the link that is provided in the instruction does not work. 
the main libraries that are needed for moving with the installation forward are:
smpt_rm3_gcc_linux_x86_amd64_static
incRehaMove_LibV3.2_lin_x86_64

Although the library is in the section #4 of the repository; however, it does not include incRehaMove_LibV3.2_lin_x86_64. 

Thanks.

**Comment by worldwidemv** [comment]
please see #7

**Comment by zahrabassiri** [comment]
It still doesn’t include incRehaMove_LibV3.2_lin_x86_64

please kindly give me this file.

**Comment by worldwidemv** [comment]
please READ my comments in #7
